const router = require('express').Router()
const Order = require('./../db/models/order')

/*

thunk will call:

axios.post('/api/order', { id : consumerid })

the route is expecting an objec with key 
of "id"

the consumer id will be generated by either 
sign up or checkout

*/

router.post('/', async (req, res, next) => {
  try {
    const newOrder = await Order.create({
      consumerId: req.body.id
    })

    res.json(newOrder)

    res.end()
  } catch (error) {
    console.error(error)
    next(error)
  }
})

router.use((req, res, next) => {
  const err = new Error('API route not found!')
  err.status = 404
  next(err)
})

module.exports = router

/*

curl -i -X POST -H "Content-Type: application/json" --data '{"id": "4"}' http://localhost:8080/api/order

*/
